name: Cache

defaults:
  run:
    shell: pwsh

on:
    workflow_dispatch:
    schedule:
    - cron: '0 * * * *'

jobs:
  Cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install PSResourceGet 1.0.4.1
        run: Install-PSResource Microsoft.PowerShell.PSResourceGet -TrustRepository
      - name: Cache PSGallery
        run: ./src/cache.ps1
      - name: Upload psgallery-xml
        uses: actions/upload-artifact@v4
        with:
          name: psgallery-xml
          path: psgallery.xml
      - name: Upload psgallery-json
        uses: actions/upload-artifact@v4
        with:
          name: psgallery-json
          path: psgallery.json
      - name: Update release assets
        run: ./src/update-release-assets.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
